apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-nginx-cert
  namespace: default   # <-- same namespace as your Ingress
spec:
  secretName: my-nginx-tls
  duration: 8760h # 1 year
  renewBefore: 720h
  commonName: nginx-demo.test
  dnsNames:
    - nginx-demo.test
  issuerRef:
    name: my-ca-issuer       # <-- the ClusterIssuer you created
    kind: ClusterIssuer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: my-ca-issuer
spec:
  tls:
    - hosts:
        - nginx-demo.test
      secretName: my-app-tls
  rules:
    - host: nginx-demo.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-app-service
                port:
                  number: 80

