apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  claimRef:
    name: grafana-pvc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/grafana
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - kworker1
            - kworker2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  claimRef:
    name: prometheus-pvc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/prometheus
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - kworker1
              - kworker2
