apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: {{ echo -n "root123" | base64 }}
  mysql-user: {{ echo -n "laravel" | base64 }}
  mysql-password: {{ echo -n "pass123" | base64 }}
  mysql-database: {{ echo -n "laravel" | base64 }}
